### ISSUE TITLE
problem when build project

### ISSUE THREAD

**Issue by babakmdi** [esptl/OpenVPNUI#1]
Hi, When i build the project nothing happened its just empty screen!

**Comment by sebastianroibu** [comment]
@babakmdi  Is it still happening  with the latest version?

**Comment by Fullbos** [comment]
The code guarantees the number of DCO adapters, but does not guarantee their operation and that a certain connection will require a certain adapter.

There is a bug in the client.
And it is as follows:

The client counts DCO adapters, but does not check that they are suitable
The client does not bind the VPN profile to a specific DCO adapter
Because of this, after Windows update, OpenVPN can get into a broken OVPN-DCO#0000 and catch Access denied

There appears to be a logic gap in the DCO adapter handling.

The client currently ensures only the number of `ovpn-dco` adapters, but does not verify that the adapters are actually usable, and does not bind a specific connection to a specific adapter (`dev-node` is not set). As a result, OpenVPN may try to open a stale/broken DCO device instance first (for example `ROOT\OVPN-DCO\0000`) and fail with `CreateFile failed ... Access is denied`.

Suggested fix:
1. Filter adapters by actual usability, not just presence.
2. Assign each connection to a specific DCO adapter.
3. Pass `dev-node` explicitly in the generated runtime config.

This should make adapter selection deterministic and avoid failures after Windows updates or broken DCO device instances.

**Comment by Fullbos** [comment]
## Bug: OpenVPN UI 1.0.13.0 fails to start on clean Windows 11 25H2 due to unhandled Win32Exception during adapter enumeration

### Summary

OpenVPN UI 1.0.13.0 fails to start on a clean installation of Windows 11 25H2. The ServiceHost process terminates before any VPN connection attempt is made.

The issue occurs during network adapter enumeration in `TapDeviceManager.GetTapDevices()` and results in an unhandled `System.ComponentModel.Win32Exception`.

### Environment

* OpenVPN UI: 1.0.13.0
* OpenVPN: 2.6.12
* Windows: 11 25H2 (clean installation)
* Reproducible on multiple clean installations
* Not observed on older Windows 11 builds (22H2)

### Event Viewer

Faulting application:

```text
Esp.Tools.OpenVPN.ServiceHost.exe
Version: 1.0.13.0
```

Exception:

```text
System.ComponentModel.Win32Exception (0x80004005): The data is invalid
```

Stack trace:

```text
at Esp.Tools.OpenVPN.Configuration.TapDeviceManager.GetTapDevices()
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at Esp.Tools.OpenVPN.Hosting.Config.OpenVPNConfigurations..ctor()
at Esp.Tools.OpenVPN.ServiceHost.OpenVPNHostService.OnStart(String[] pArgs)
at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
```

### Behaviour

The ServiceHost crashes during startup while enumerating TAP/DCO adapters.

As a result:

* `openvpnui_control` pipe is closed
* UI cannot communicate with ServiceHost
* VPN connection never reaches the OpenVPN process
* No TLS handshake or certificate validation occurs

### Expected Behaviour

If Windows returns invalid adapter data, the service should:

* skip the invalid adapter entry
* log a warning
* continue enumerating remaining adapters

The ServiceHost should not terminate because of a single malformed or unsupported network adapter entry.

### Additional Observation

The issue appears to be triggered by a specific system dependency/configuration present on clean Windows 11 25H2 installations.

After installing the required Microsoft Visual C++ Redistributable package, the VPN client starts and operates normally.

It may therefore be worth:

1. Verifying all runtime dependencies during installation.
2. Bundling/installing required VC++ runtimes automatically.
3. Adding defensive exception handling around adapter enumeration to prevent ServiceHost termination.
